from typing import List, Optional, Tuple

__version__: str

class Partition:
    """A partition of the finite universe ``{0, ..., n-1}``.

    Block labels carry no information: ``Partition([0, 0, 1, 1])`` and
    ``Partition([7, 7, 3, 3])`` are equal and hash equal.

    ``refines`` means *finer*, so ``discrete(n)`` is the least element. ``meet`` is
    the common refinement and ``join`` the common coarsening; much of the literature
    uses the order-dual. The order is partial.
    """

    def __init__(self, ids: List[int]) -> None: ...
    @classmethod
    def discrete(cls, size: int) -> "Partition": ...
    @classmethod
    def indiscrete(cls, size: int) -> "Partition": ...
    @classmethod
    def from_blocks(cls, size: int, blocks: List[List[int]]) -> "Partition": ...

    def block_count(self) -> int: ...
    def blocks(self) -> List[List[int]]: ...
    def ids(self) -> List[int]: ...
    def block_of(self, element: int) -> int: ...

    def meet(self, other: "Partition") -> "Partition": ...
    def join(self, other: "Partition") -> "Partition": ...
    def refines(self, other: "Partition") -> bool: ...

    def logical_entropy(self) -> float: ...
    def dit_count(self) -> int: ...
    def distance(self, other: "Partition") -> float: ...
    def mutual_information(self, other: "Partition") -> float: ...
    def divergence(self, other: "Partition") -> float: ...
    def rand_agreement(self, other: "Partition") -> float: ...
    def jaccard(self, other: "Partition") -> Optional[float]: ...

    def weighted_entropy(self, weights: List[int]) -> Tuple[int, int]: ...
    def cross_entropy(self, p: List[int], q: List[int]) -> Tuple[int, int]: ...

    def __len__(self) -> int: ...
    def __and__(self, other: "Partition") -> "Partition": ...
    def __or__(self, other: "Partition") -> "Partition": ...
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: "Partition") -> bool: ...
    def __lt__(self, other: "Partition") -> bool: ...
    def __ge__(self, other: "Partition") -> bool: ...
    def __gt__(self, other: "Partition") -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

def dit_xor_count(a: Partition, b: Partition) -> int: ...
def destr(a: Partition, b: Partition) -> int: ...
def creat(a: Partition, b: Partition) -> int: ...
