from typing import List, Optional, Tuple

__version__: str

class Partition:
    """A partition of the finite universe ``{0, ..., n-1}``.

    Block labels carry no information: ``Partition([0, 0, 1, 1])`` and
    ``Partition([7, 7, 3, 3])`` are equal and hash equal.

    ``refines`` means *finer*. The operations are ``refine`` (common refinement) and
    ``coarsen`` (common coarsening); the names say what they do, because ``meet`` and
    ``join`` name opposite operations in the two conventions the literature uses.
    """

    def __init__(self, ids: List[int]) -> None: ...
    @classmethod
    def discrete(cls, size: int) -> "Partition": ...
    @classmethod
    def indiscrete(cls, size: int) -> "Partition": ...
    @classmethod
    def from_blocks(cls, size: int, blocks: List[List[int]]) -> "Partition": ...

    def block_count(self) -> int: ...
    def blocks(self) -> List[List[int]]: ...
    def ids(self) -> List[int]: ...
    def block_of(self, element: int) -> int: ...

    # `meet`/`join` were removed in 0.2.0: they name opposite operations in the two
    # conventions the literature uses. These names say what the operation does.
    def refine(self, other: "Partition") -> "Partition": ...
    def coarsen(self, other: "Partition") -> "Partition": ...
    def refines(self, other: "Partition") -> bool: ...

    def logical_entropy(self) -> float: ...
    def dit_count(self) -> int: ...
    def ditset_xor_distance(self, other: "Partition") -> float: ...
    def mutual_information(self, other: "Partition") -> float: ...
    def logical_divergence(self, other: "Partition") -> float: ...
    def rand_agreement(self, other: "Partition") -> float: ...
    def dit_set_jaccard(self, other: "Partition") -> Optional[float]: ...

    def logical_entropy_weighted(self, weights: List[int]) -> Tuple[int, int]: ...
    def cross_entropy_weighted(self, p: List[int], q: List[int]) -> Tuple[int, int]: ...

    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

def dit_xor_count(a: Partition, b: Partition) -> int: ...
def destr(a: Partition, b: Partition) -> int: ...
def creat(a: Partition, b: Partition) -> int: ...
